ToGoDelivery/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ToGoDelivery.Models
{
    public class Order
    {
        [Key, Required]
        public int OrderId { get; set; }

        //https://entityframework.net/knowledge-base/41274794/how-do-i-add-a-foreign-key-to-identity-user-in-ef-core-
        //[Required, ForeignKey(nameof(ApplicationUser))]
        //public Guid CustomerId { get; set; }
        //public virtual ApplicationUser Customer { get; set; }
        [Required]
        public string CustomerId { get; set; }

        [ForeignKey("CustomerId")]
        public ApplicationUser Customer { get; set; }

        [Required]
        public DateTime DateCreated { get; set; }

        [Required]
        public bool IsActive { get; set; }

        public decimal FinalTotalCost { get; set; }

        public bool IsFavorite { get; set; }
        
        //[ForeignKey(nameof(ApplicationUser))]
        //public ApplicationUser DriverId { get; set; }

        //public virtual ApplicationUser Driver { get; set; }

        //public string DriverId { get; set; }

        //[ForeignKey("DriverId")]
        //public ApplicationUser Driver { get; set; }

        public bool IsPrepared { get; set; }

        public bool IsFinalized { get; set; }

        public DateTime DateFinalized { get; set; }



    }
}

ToGoDelivery/Controllers/MenuController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToGoDelivery.Data;
using ToGoDelivery.Services;

namespace ToGoDelivery.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        //This menu controller is meant to host both products and services in the views utilizing the product and service controllers and services
        // GET: Menu
        public ActionResult Index()
        {
            //var pctrl = new ProductController();
            //var psvc = pctrl.CreateProductService();
            //var pmodel = psvc.GetProducts();
            var psvc = CreateProductService();


            var sctrl = new ServiceController();
            //var ssvc = sctrl.CreateServiceService();
            //var smodel = ssvc.GetServices();
            var ssvc = CreateServiceService();

            //dynamic model = new ExpandoObject();
            //model.Products = psvc.GetProducts();
            //model.Services = ssvc.GetServices();
            ViewBag.Products = psvc.GetProducts();
            ViewBag.Services = ssvc.GetServices();

            //return View(model);
            return View();
        }
        private ProductService CreateProductService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ProductService(userId);
            return service;
        }
        private ServiceService CreateServiceService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var svc = new ServiceService(userId);
            return svc;
        }
    }
}

ToGoDelivery/Controllers/OrderController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToGoDelivery.Data;
using ToGoDelivery.Models.Order;
using ToGoDelivery.Services;

namespace ToGoDelivery.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Order
        public ActionResult AdminIndex()
        {
            var svc = CreateOrderService();
            var model = svc.GetAllOrders();

            return View(model);
        }

        public ActionResult CustomerIndex()
        {
            var svc = CreateOrderService();
            var model = svc.GetOrdersByCustomer();

            return View(model);
        }

        public ActionResult CustomerCart()
        {
            var svc = CreateOrderService();
            if (svc.CheckForCurrentCart())
            {
                var model = svc.GetMostRecentOrder();
                return View(model);
            }
            return Create();
        }

        public ActionResult Create()
        {
            var svc = CreateOrderService();

            if (svc.CreateOrder())
            {
                TempData["SaveResult"] = "Your order was created.";
                return RedirectToAction("CustomerIndex");
            }

            ModelState.AddModelError("", "Order could not be created.");

            return RedirectToAction("CustomerIndex");
        }

        public ActionResult Details(int id)
        {
            var svc = CreateOrderService();
            var model = svc.GetOrderById(id);

            return View(model);
        }

        public ActionResult DetailById(int id)
        {
            var svc = CreateOrderService();
            var model = svc.GetOrderDetailById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var svc = CreateOrderService();
            var detail = svc.GetOrderById(id);
            var model =
                new OrderEdit
                {
                    OrderId = detail.OrderId,
                    IsActive = detail.IsActive,
                    IsFavorite = detail.IsFavorite,
                    IsPrepared = detail.IsPrepared,
                    IsFinalized = detail.IsFinalized
                };

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OrderEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.OrderId != id)
            {
                ModelState.AddModelError("", "ID Mismatch");
                return View(model);
            };

            var svc = CreateOrderService();

            if (svc.UpdateOrder(model))
            {
                TempData["SaveResult"] = "Your order was updated.";
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("AdminIndex");
                }
                return RedirectToAction("CustomerIndex");
            }

            ModelState.AddModelError("", "Your order could not be updated.");
            return View(model);
        }

        public ActionResult Finalize(int id)
        {
            var svc = CreateOrderService();

            if (svc.FinalizeOrder(id))
            {
                TempData["SaveResult"] = "Your order was finalized.";
                return RedirectToAction("CustomerIndex");
            }

            ModelState.AddModelError("", "Your order could not be finalized.");
            return RedirectToAction("CustomerCart");
        }

        [ActionName("SoftDelete")]
        public ActionResult SoftDelete(int id)
        {
            var svc = CreateOrderService();
            var model = svc.GetOrderById(id);

            return View(model);
        }


        [ActionName("SoftDelete"), HttpPost, ValidateAntiForgeryToken]
        public ActionResult SoftDeletePost(int id)
        {
            var svc = CreateOrderService();

            svc.SoftDeleteOrder(id);

            TempData["SaveResult"] = "Your order was (soft) deleted.";

            return RedirectToAction("AdminIndex");

        }

        private Services.OrderService CreateOrderService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new Services.OrderService(userId);
            return service;
        }
    }
}

ToGoDelivery/Controllers/OrderProductController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToGoDelivery.Data;

namespace ToGoDelivery.Controllers
{
    public class OrderProductController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        public ActionResult Create(int productId)
        {
            var svc = CreateOrderProductService();
            int orderId = svc.GetCurrentOrderId();

            if (!svc.CheckForCurrentOrderProduct(orderId, productId))
            {
                if (svc.CreateOrderProduct(orderId, productId))
                {
                    TempData["SaveResult"] = "Product was added to your cart.";
                    return RedirectToAction("Index", "Menu");
                }

                ModelState.AddModelError("", "Product could not be added to your order. Have you started a new order?");

                return RedirectToAction("Index", "Menu");
            }

            return AddProductToOrderProduct(productId);
        }

        public ActionResult AddProductToOrderProduct(int productId)
        {
            var svc = CreateOrderProductService();
            int orderId = svc.GetCurrentOrderId();

            if(svc.AddProduct(orderId, productId))
            {
                TempData["SaveResult"] = "One more was added to your cart.";
                return RedirectToAction("Index", "Menu");
            }

            ModelState.AddModelError("", "Product could not be added to your order. Have you started a new order?");

            return RedirectToAction("Index", "Menu");
        }

        //public ActionResult GetOrderProducts(int orderId) //might not need this at all? I'm pulling order details from the orderdetail
        //{
        //    var svc = CreateOrderProductService();
        //    ViewBag.OrderProducts = svc.GetOrderProductsByOrderId(orderId);

        //    return ViewBag.OrderProducts;//View(model); //This might need to be packaged differently since there is no view... may need to make an IEnumerable instead of action???
        //}

        private Services.OrderProductService CreateOrderProductService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new Services.OrderProductService(userId);
            return service;
        }

        public ActionResult Delete(int productId)
        {
            var svc = CreateOrderProductService();
            int orderId = svc.GetCurrentOrderId();

            if (svc.DeleteOrderProduct(orderId, productId))
            {
                TempData["SaveResult"] = "Product was removed from your cart.";
                return RedirectToAction("CustomerCart", "Order");
            }

            ModelState.AddModelError("", "Product could not be removed from your cart.");

            return RedirectToAction("CustomerCart", "Order");
        }

    }
}

ToGoDelivery/Controllers/OrderServiceController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToGoDelivery.Data;
using ToGoDelivery.Models;

namespace ToGoDelivery.Controllers
{
    public class OrderServiceController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        public ActionResult Create(int serviceId)
        {
            var svc = CreateOrderServiceService();
            int orderId = svc.GetCurrentOrderId();

            if (!svc.CheckForCurrentOrderService(orderId, serviceId))
            {
                if (svc.CreateOrderService(orderId, serviceId))
                {
                    TempData["SaveResult"] = "Service was added to your cart.";
                    return RedirectToAction("Index", "Menu");
                }

                ModelState.AddModelError("", "Service could not be added to your order. Have you started a new order?");

                return RedirectToAction("Index", "Menu");
            }

            TempData["SaveResult"] = "You already have this service in your cart.";
            return RedirectToAction("Index", "Menu");
        }

        //public ActionResult GetOrderServices(int orderId) //might not need this at all? I'm pulling order details from the orderdetail
        //{
        //    var svc = CreateOrderServiceService();
        //    ViewBag.OrderServices = svc.GetOrderServicesByOrderId(orderId);

        //    return ViewBag.OrderServices;//View(model); //This might need to be packaged differently since there is no view... may need to make an IEnumerable instead of action???
        //}


        public ActionResult Delete(int serviceId)
        {
            var svc = CreateOrderServiceService();
            int orderId = svc.GetCurrentOrderId();

            if (svc.DeleteOrderService(orderId, serviceId))
            {
                TempData["SaveResult"] = "Service was removed from your cart.";
                return RedirectToAction("CustomerCart", "Order");
            }

            ModelState.AddModelError("", "Service could not be removed from your cart.");

            return RedirectToAction("CustomerCart", "Order");
        }

        private Services.OrderServiceService CreateOrderServiceService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new Services.OrderServiceService(userId);
            return service;
        }

    }
}

ToGoDelivery/Views/Order/AdminIndex.cshtml
@model IEnumerable<ToGoDelivery.Models.Order.OrderListItem>
@{
    ViewBag.Title = "AdminIndex";
}
<div class="jumbotron" style="background-color:#e3fefe">
    <h2 style="font-weight:bolder">Orders</h2>
    @*<div>
            @Html.ActionLink("Create New Order", "Create")
        </div>*@
    @if (TempData.ContainsKey("SaveResult"))
    {
        <div class="alert alert-success fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span>&times;</span>
            </button>
            @TempData["SaveResult"]
        </div>
    }

    <div>
        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.OrderId)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Customer.Email)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.FinalTotalCost)
                </th>
                <th></th>
            </tr>
            @foreach (var order in Model)
            {
                if (order.IsActive)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(r => order.DateCreated)
                    </td>
                    <td>
                        @Html.DisplayFor(r => order.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(r => order.Customer.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(r => order.FinalTotalCost)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = order.OrderId }) |
                        @Html.ActionLink("Details", "Details", new { id = order.OrderId }) |
                        @Html.ActionLink("Delete", "SoftDelete", new { id = order.OrderId })
                    </td>
                </tr>
                }
            }
        </table>
    </div>
</div>

ToGoDelivery/Views/Order/CustomerCart.cshtml
@model ToGoDelivery.Models.Order.OrderDetail

@{
    ViewBag.Title = "Customer Cart";
}
<div class="jumbotron" style="background-color:#e3fefe">
    <h2 style="font-weight:bolder">Shopping Cart</h2>
    @Html.HiddenFor(model => model.OrderId)

    @*<div>
        @Html.ActionLink("Start a New Order", "Create", null, new { id = "myLink" }) |
        @Html.ActionLink("Back to Menu", "Index", "Menu")

    </div>*@

    @if (TempData.ContainsKey("SaveResult"))
    {
        <div class="alert alert-success fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span>&times;</span>
            </button>
            @TempData["SaveResult"]
        </div>
    }
    <br />
    @*<table>
            <tr>
                <th style="font-weight:bolder">Products</th>
            </tr>
        </table>*@
    @*<div style="font-size: large">Products</div>*@

    <table class="table table-hover">
        @*<tr>
                <th>Name</th>

                <th>Count</th>

                <th>Cost</th>

                <th></th>

            </tr>*@
        <tr>
            <td><h3>Products</h3></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var op in Model.OrderProducts)
        {
            <tr>
                <td>
                    @op.ProductName
                </td>
                <td>
                    X @op.ProductCount
                </td>
                <td>
                    @op.Cost.ToString("C")
                </td>
                <td>
                    @Html.ActionLink("Remove", "Delete", "OrderProduct", new { productId = op.ProductId }, null)
                </td>

            </tr>
        }
    <tr>
        <td><h3>Services</h3></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        @foreach (var os in Model.OrderServices)
        {
            <tr>
                <td>
                    @os.ServiceName
                </td>
                <td style="color:white"></td>
                <td>
                    @os.Cost.ToString("C")

                </td>
                <td>
                    @Html.ActionLink("Remove", "Delete", "OrderService", new { serviceId = os.ServiceId }, null)
                </td>
            </tr>
        }
    </table>
    <br />
    @*<table>
            <tr>
                <th style="font-weight:bolder" class="text-center">Services</th>
            </tr>
        </table>*@
    @*<div style="font-size: large">Services</div>

        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th style="color:white"></th>
                <th>Cost</th>
                <th></th>

            </tr>

        </table>*@
    <div style="font-weight:bolder">
        <div style="text-align:right">
            Running Total Cost: @Html.DisplayFor(r => Model.TotalCostCalculator)
            @*, @style="color: black; border: 1px solid grey;"*@


        </div>
    </div>
    <div>
        @Html.ActionLink("Finalize Order", "Finalize", "Order", new { id = Model.OrderId }, new { @class = "btn btn-success" })

    </div>

</div>

ToGoDelivery/Views/Order/CustomerIndex.cshtml
@model IEnumerable<ToGoDelivery.Models.Order.OrderListItem>
@{
    ViewBag.Title = "CustomerIndex";
}
<div class="jumbotron" style="background-color:#e3fefe">
    <h2 style="font-weight:bolder">Orders</h2>
    <div>
        @Html.ActionLink("Create New Order", "Create", null, new { id = "myLink" }) |
        @Html.ActionLink("View Your Cart", "CustomerCart")
    </div>

    @if (TempData.ContainsKey("SaveResult"))
    {
        <div class="alert alert-success fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span>&times;</span>
            </button>
            @TempData["SaveResult"]
        </div>
    }

    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.FinalTotalCost)
            </th>
            <th></th>
        </tr>
        @foreach (var order in Model)
        {
            //if (order.IsActive)
            //{
            <tr>
                <td>
                    @Html.DisplayFor(r => order.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(r => order.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(r => order.FinalTotalCost)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = order.OrderId }) |
                    @Html.ActionLink("Edit", "Edit", new {id = order.OrderId})
                </td>
            </tr>
            //}
        }
    </table>
</div>

ToGoDelivery/Views/Order/DetailById.cshtml
@model ToGoDelivery.Models.Order.OrderDetail

@{
    ViewBag.Title = "DetailById";
}
<div class="jumbotron" style="background-color:#e3fefe">
    <h2 style="font-weight:bolder">More Order Details</h2>
    @Html.HiddenFor(model => model.OrderId)

    @if (TempData.ContainsKey("SaveResult"))
    {
        <div class="alert alert-success fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span>&times;</span>
            </button>
            @TempData["SaveResult"]
        </div>
    }

    <div>@Html.DisplayNameFor(model => model.DateCreated): @Html.DisplayFor(model => model.DateCreated)</div>

    <table class="table table-hover">
        <tr>
            <th>Name</th>

            <th>Count</th>

            <th>Cost</th>
            <th></th>
        </tr>
        @foreach (var op in Model.OrderProducts)
        {
            <tr>

                <td>
                    @Html.DisplayFor(r => op.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(r => op.ProductCount)
                </td>
                <td>
                    @Html.DisplayFor(r => op.Cost)
                </td>
            </tr>
        }
        @foreach (var os in Model.OrderServices)
        {
            <tr>
                <td>
                    @Html.DisplayFor(r => os.ServiceName)
                </td>
                <td>
                    1
                </td>
                <td>
                    @Html.DisplayFor(r => os.Cost)
                </td>

            </tr>
        }
    </table>
    <div style="font-weight:bold">@Html.DisplayNameFor(model => model.FinalTotalCost): @Html.DisplayFor(model => model.FinalTotalCost)</div>
    <br />
    <div>@Html.ActionLink("Back to Order Detail Overview", "Details", new { id = Model.OrderId }) </div>


</div>

ToGoDelivery/Views/Order/Details.cshtml
@model ToGoDelivery.Models.Order.OrderDetail

@{
    ViewBag.Title = "Details";
}
<div class="jumbotron" style="background-color:#e3fefe">

    <h2 style="font-weight: bolder">Details</h2>

    <div>
        <h4>Order Detail Overview</h4>
        <hr />
        @Html.HiddenFor(model => model.CustomerId)
        @Html.HiddenFor(model => model.Customer)


        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.OrderId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FinalTotalCost)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FinalTotalCost)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFavorite)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFavorite)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsPrepared)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsPrepared)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFinalized)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFinalized)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateFinalized)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateFinalized)
            </dd>

        </dl>
    </div>
    <div>
        @if (User.IsInRole("Admin"))
        {
            <div>
                @Html.ActionLink("Back to List", "AdminIndex") |
                @Html.ActionLink("Edit", "Edit", new { id = Model.OrderId }) |
                @Html.ActionLink("Get More Details", "DetailById", new { id = Model.OrderId }) |
                @Html.ActionLink("Back to Your Orders", "CustomerIndex")
            </div>
        }
        else
        {
            <div>
                @Html.ActionLink("Get More Details", "DetailById", new { id = Model.OrderId }) |
                @Html.ActionLink("Back to Your Orders", "CustomerIndex")
            </div>
        }
    </div>
</div>

ToGoDelivery/Views/Order/Edit.cshtml
@model ToGoDelivery.Models.Order.OrderEdit

@{
    ViewBag.Title = "Edit";
}
<div class="jumbotron" style="background-color:#e3fefe">
    <h2 style="font-weight:bold">Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Order Edit</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.OrderId)

            <div class="form-group">
                @Html.LabelFor(model => model.IsFavorite, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsFavorite)
                        @Html.ValidationMessageFor(model => model.IsFavorite, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @if (User.IsInRole("Admin"))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsPrepared, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsPrepared)
                            @Html.ValidationMessageFor(model => model.IsPrepared, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsFinalized, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsFinalized)
                            @Html.ValidationMessageFor(model => model.IsFinalized, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            }
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @if (User.IsInRole("Admin"))
        {
            <div>
                @Html.ActionLink("Back to List", "AdminIndex") |
                @Html.ActionLink("Order Detail", "Details", new { id = Model.OrderId })

            </div>
        }
        else
        {
            <div>
                @Html.ActionLink("Back to Your Orders", "CustomerIndex") |
                @Html.ActionLink("Order Detail", "Details", new { id = Model.OrderId })
            </div>
        }

    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToGoDelivery/Views/Order/SoftDelete.cshtml
@model ToGoDelivery.Models.Order.OrderDetail

@{
    ViewBag.Title = "SoftDelete";
}
<div class="jumbotron" style="background-color:#e3fefe">

    <h2 style="font-weight:bolder">Soft Delete</h2>

    <h3>Are you sure you want to make this order inactive?</h3>
    <div>
        <h4>Order Detail</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.OrderId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FinalTotalCost)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FinalTotalCost)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFavorite)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFavorite)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsPrepared)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsPrepared)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsFinalized)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsFinalized)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateFinalized)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateFinalized)
            </dd>

        </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "AdminIndex")
        </div>
    }
</div>
</div>